### ISSUE TITLE
CMSSW broken by EL9 upgrades on LXPLUS

### ISSUE THREAD

**Issue by lk11235** [hexutils/HexUtils#88]
Propose to use CMSSW_13 or CMSSW_14. 

Or even better, if CMSSW is not necessary at the HexUtils level, we can load a LCG env because this will be better maintained, include more useful/consistent deps, and be consistent with any SWAN work. 

https://ep-dep-sft.web.cern.ch/document/lcg-releases

e.g. `source /cvmfs/sft.cern.ch/lcg/views/LCG_104a_cuda/x86_64-el9-gcc11-opt/setup.sh`

**Comment by MohitS704** [comment]
Recommend to use `CMSSW_14_0_0`
